import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Sidenavbar from "../src/components/navbar"
import WebsiteMain from "./website"
import GraphicsMain from "./graphics"

import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';

export default function dashboard() {
  // const cards = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  return (
    <div>
      <Head>
        <title>Dashboard | Kikiaka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {/* <ThemeProvider theme={mdTheme}> */}
          <Box sx={{ display: "flex" }}>
            <CssBaseline />
            <Sidenavbar />
          
            <Box className={styles.tes}
              component="main"
              sx={{
                backgroundColor: (theme) =>
                  theme.palette.mode === "light"
                    ? theme.palette.grey[100]
                    : theme.palette.grey[900],
                flexGrow: 1,
                height: "100vh",
                overflow: "auto",
              }}
            >
              <Toolbar />

              <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
                <Grid container spacing={3}>
                  {/* Chart */}
                  <Grid item xs={12} md={12} lg={12}>
                    <Paper
                      sx={{
                        p: 2,
                        display: "flex",
                        flexDirection: "column",
                        height: 400,
                      }}
                    >
                      Dashboard Session
                    </Paper>
                  </Grid>
                </Grid>
              </Container>
              {/* End Main Dashboard */}
              
              {/* Main Graphics */}
              <GraphicsMain />
              {/* End Main Graphics */}
              
              {/* Main Website */}
              <WebsiteMain/>
              {/* <Container sx={{ py: 8 }} maxWidth="md">
                <Grid container spacing={4}>
                  {cards.map((card) => (
                    <Grid item key={card} xs={12} sm={6} md={4}>
                      <Card
                        sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}
                      >
                        <CardMedia
                          component="img"
                          sx={{
                            pt: '56.25%',
                          }}
                          image=""
                          alt="random"
                        />
                        <CardContent sx={{ flexGrow: 1 }}>
                          <Typography gutterBottom variant="h5" component="h2">
                            Heading
                          </Typography>
                          <Typography>
                            This is a media card. You can use this section to describe the
                            content.
                          </Typography>
                        </CardContent>
                        <CardActions>
                          <Button size="small">View</Button>
                          <Button size="small">Edit</Button>
                        </CardActions>
                      </Card>
                    </Grid>
                  ))}
                </Grid>
              </Container> */}
              {/* End Main Website */}

            </Box>
          </Box>
        {/* </ThemeProvider> */}
      </main>
    </div>
  )
}