import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kikiaka Digital Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to new site <a href="https://nextjs.org">Kikiaka Digital Projects</a>
        </h1>

        <p className={styles.description}>
          {/* Get started by editing{' '} */}
          <code className={styles.code}>Follow My Instagram on @kikiaka.id</code>
        </p>

        <div className={styles.grid}>
            <Link href="/dashboard" className={styles.card}> 
                <h2>Portfolio Site &rarr;</h2>
                <p>Please visit here to see us further</p>
            </Link>

            {/* <Link href="/post/abc" className={styles.card}> 
            <h2>Graphics &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Link> */}

          <Link href="/contact" className={styles.card}> 
            <h2>Call Me &rarr;</h2>
            <p>If you want to collaborate, please contact us</p>
          </Link>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Call &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
          
        </div>
      </main>

      <footer className={styles.footer}>
        <p> @2022 - Kikiaka Digital Project</p>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
