import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Sidenavbar from "../src/components/navbar";
import WebsiteMain from "./website";
import GraphicsMain from "./graphics";
import Dashboard from "./dashboard";

export default function main() {
  return (
    <div>
      <Head>
        <title>Main Menu | Kikiaka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <ThemeProvider theme={mdTheme}> */}
        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <Sidenavbar />

          <Box
            className={styles.tes}
            component="main"
            sx={{
              backgroundColor: (theme) =>
                theme.palette.mode === "light"
                  ? theme.palette.grey[100]
                  : theme.palette.grey[900],
              flexGrow: 1,
              height: "100vh",
              overflow: "auto",
            }}
          >
            <Toolbar />
            {/* Main Dashboard */}
            <Dashboard />
            {/* End Main Dashboard */}

            {/* Main Graphics */}
            <GraphicsMain />
            {/* End Main Graphics */}

            {/* Main Website */}
            <WebsiteMain />
            {/* End Main Website */}
          </Box>
        </Box>
        {/* </ThemeProvider> */}
      </main>
    </div>
  );
}
